/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotellerio;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;

/**
 *
 * @author  Hemanth Eagle
 */
public class Check_Availability extends javax.swing.JFrame {

    /**
     * Creates new form check_Availability
     */
    public Check_Availability() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        siNGle = new javax.swing.JTextField();
        doUUble = new javax.swing.JTextField();
        doUPlex = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        check_02 = new javax.swing.JButton();
        reset_3 = new javax.swing.JButton();
        cancel_3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        single_err = new javax.swing.JLabel();
        double_err = new javax.swing.JLabel();
        douplex_err = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Single");

        jLabel2.setText("Double");

        jLabel4.setText("Douplex");

        siNGle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                siNGleKeyTyped(evt);
            }
        });

        doUUble.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                doUUbleKeyTyped(evt);
            }
        });

        doUPlex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                doUPlexKeyTyped(evt);
            }
        });

        jLabel5.setText("Enter the rooms quantity to  check for availability ..");

        check_02.setText("Check");
        check_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_02ActionPerformed(evt);
            }
        });

        reset_3.setText("Reset");
        reset_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_3ActionPerformed(evt);
            }
        });

        cancel_3.setText("Cancel");
        cancel_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_3ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotellerio/images/roomie.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(siNGle, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(doUUble, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(single_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(doUPlex, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(double_err, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(douplex_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(reset_3)
                .addGap(68, 68, 68)
                .addComponent(check_02)
                .addGap(58, 58, 58)
                .addComponent(cancel_3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(siNGle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(single_err, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(doUUble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(double_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doUPlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(douplex_err, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_02)
                    .addComponent(reset_3)
                    .addComponent(cancel_3))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void check_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_02ActionPerformed

        if(siNGle.getText().trim().isEmpty() && doUUble.getText().trim().isEmpty() && doUPlex.getText().trim().isEmpty())
        {
            single_err.setText("*This field is required");
            single_err.setForeground(Color.red);
            double_err.setText("*This field is required");
            double_err.setForeground(Color.red);
            douplex_err.setText("*This field is required");
            douplex_err.setForeground(Color.red);
        }
        else if(siNGle.getText().trim().isEmpty())
        {
          single_err.setText("*This field is required");
            single_err.setForeground(Color.red);
            double_err.setText("");
            douplex_err.setText("");
        }
        else if(doUUble.getText().trim().isEmpty())
        {
          single_err.setText("");
            double_err.setText("*This field is required");
            double_err.setForeground(Color.red);
            douplex_err.setText("");
        }
        else if(doUPlex.getText().trim().isEmpty())
        {
            single_err.setText("");
            double_err.setText("");
            douplex_err.setText("*This field is required");
            douplex_err.setForeground(Color.red);
        }
        else{
        try  {
           int SIngle=0,DOuuble=0,DOuplex=0;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/hotellerio";
            String user = "root";
            String pass = "1.414magiC";
            Connection con = DriverManager.getConnection(url,user,pass);
            String sql = " select * from room_availability";
            PreparedStatement ps=con.prepareStatement(sql);
			ResultSet rs=ps.executeQuery();
                        while(rs.next()){
                             SIngle =  rs.getInt(2);
                             DOuuble = rs.getInt(3);
                             DOuplex = rs.getInt(4);
                        }
                        int a = SIngle-Integer.valueOf(siNGle.getText());
                        int b = DOuuble-Integer.valueOf(doUUble.getText());
                        int c = DOuplex-Integer.valueOf(doUPlex.getText());
                        
JOptionPane.showMessageDialog(null,"rooms left after booking will be "+a+" single rooms, "+b+" double rooms, "+c+" douplex rooms","Display Message", JOptionPane.INFORMATION_MESSAGE);
            con.close();
            this.setVisible(false);
            new Room_Section().setVisible(true);
        
        } 
        catch (ClassNotFoundException | SQLException e) {
            System.out.println("no result found "+e);
        }  }      // TODO add your handling code here:
    }//GEN-LAST:event_check_02ActionPerformed

    private void reset_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_3ActionPerformed
            siNGle.setText("");
            doUUble.setText("");
            doUPlex.setText("");
            single_err.setText("");
            double_err.setText("");
            douplex_err.setText("");
    }//GEN-LAST:event_reset_3ActionPerformed

    private void cancel_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_3ActionPerformed
        this.setVisible(false);
        new Room_Section().setVisible(true);
    }//GEN-LAST:event_cancel_3ActionPerformed

    private void siNGleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_siNGleKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_siNGleKeyTyped

    private void doUUbleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doUUbleKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_doUUbleKeyTyped

    private void doUPlexKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doUPlexKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_doUPlexKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_Availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_Availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_Availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_Availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_Availability().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_3;
    private javax.swing.JButton check_02;
    private javax.swing.JTextField doUPlex;
    private javax.swing.JTextField doUUble;
    private javax.swing.JLabel double_err;
    private javax.swing.JLabel douplex_err;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton reset_3;
    private javax.swing.JTextField siNGle;
    private javax.swing.JLabel single_err;
    // End of variables declaration//GEN-END:variables
}
