/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotellerio;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author  Hemanth Eagle
 */
public class Generate_Bill extends javax.swing.JFrame {

    /**
     * Creates new form Generate_Bill
     */
    public Generate_Bill() {
        initComponents();
    }
    public Generate_Bill(int Cust_id)
    {
        initComponents();
        int num = Cust_id;
        try {
            Connection con =DBConnect.connect();
            String sql1 = "select cust_name from customer_details where cust_ID=?";
            PreparedStatement ps1=con.prepareStatement(sql1);
            ps1.setInt(1, num);
            ResultSet rs1=ps1.executeQuery();
            String c_name=new String();
            while(rs1.next())
            {
                c_name=rs1.getString(1);
                Customer_name.setText(c_name);
            }
            String room = "Select cost_s,cost_db,cost_dp from room_details where cust_ID = ?";
            PreparedStatement psr=con.prepareStatement(room);
            psr.setInt(1, num);
            ResultSet rsr=psr.executeQuery();
            int arr[] = new int[3];
            while(rsr.next())
            {
                arr[0] = rsr.getInt(1);
                arr[1] = rsr.getInt(2);
                arr[2] = rsr.getInt(3);
            }
            int sum = arr[0]+arr[1]+arr[2];
            String tot = "" +sum+ "Rs/-";
            room_rent.setText(tot);
            String food = "select total_price from order_food where cust_id = ?";
             PreparedStatement psf=con.prepareStatement(food);
             psf.setInt(1, num);
             ResultSet rsf=psf.executeQuery();
             ArrayList<Float> li = new ArrayList();
             while(rsf.next())
             {
                 li.add(rsf.getFloat(1));
             }
            float sum1 = 0;
            for(int i=0;i<li.size();i++)
            {
                sum1 = sum1+li.get(i);
            }
            String f = ""+sum1+ "Rs/-";
            food_rent.setText(f);
            String sqll= "select total_price from order_laundry where cust_id=?";
            PreparedStatement psl=con.prepareStatement(sqll);
            psl.setInt(1, num);
            ResultSet rsl=psl.executeQuery();
            ArrayList<Float> ls = new ArrayList();
            while(rsl.next())
            {
                ls.add(rsl.getFloat(1));
            }
            float sum2=0;
            for(int i=0;i<ls.size();i++)
            {
                sum2=sum2+ls.get(i);
            }
            String l=""+sum2+ "Rs/-";
            laudry_rnt.setText(l);
            String sqlt = "select price from transport_table where cust_Id = ?";
             PreparedStatement pst=con.prepareStatement(sqlt);
            pst.setInt(1, num);
            ResultSet rst=pst.executeQuery();
            int cost = 0;
            while(rst.next())
            {
                cost = rst.getInt(1);
                String t = ""+cost+" Rs/-";
                transport_rent.setText(t);
            }
            float tot_cost = sum + sum1 + sum2 + cost;
            String finalcost = ""+tot_cost+" Rs/-";
            total_amount.setText(finalcost);
            float lss = (float)(tot_cost*10)/100;
            String ppp = Float.toString(lss);
            less.setText("-"+ppp+" Rs/-");
            float gs = (float)(tot_cost*12)/100;
            String qqq = Float.toString(gs);
            gst.setText("+"+qqq+" Rs/-");
            float net = (float)(tot_cost-lss+gs);
            String ntt = Float.toString(net);
            net_total.setText("+"+ntt+" Rs/-");
            Random rn=new Random();
            int db= rn.nextInt(1000000);
            long millis=System.currentTimeMillis();
            java.sql.Timestamp date ;
            date = new java.sql.Timestamp(millis);
            String rnn = Integer.toString(db);
            String dbb = date.toString();
            bill_number.setText(rnn);
            date_current.setText(dbb);
            String cucu = Integer.toString(Cust_id);
            id_current.setText(cucu);
            
        } catch (Exception e) {
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Customer_name = new javax.swing.JLabel();
        date_current = new javax.swing.JLabel();
        id_current = new javax.swing.JLabel();
        bill_number = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        room_rent = new javax.swing.JLabel();
        food_rent = new javax.swing.JLabel();
        laundry_rent = new javax.swing.JLabel();
        transport_rent = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        total_amount = new javax.swing.JLabel();
        less = new javax.swing.JLabel();
        gst = new javax.swing.JLabel();
        net_total = new javax.swing.JLabel();
        laudry_rnt = new javax.swing.JLabel();
        donedone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("HOTEL MUNNI");

        jLabel2.setText("2-4-391/8, MG Road, ");

        jLabel3.setText("Sirpur Kaghaznagar, Adilabad - 504296l");

        jLabel4.setText("Ph. +91 -8738-236588");

        jLabel5.setText("HOTEL MUNNI BILL");

        jLabel6.setText("Name:");

        jLabel7.setText("Date:");

        jLabel8.setText("ID:");

        jLabel9.setText("Bill No.:");

        jLabel10.setText("----------------------------------------------------------------------------------------------------------------------------------");

        jLabel11.setText("S.No");

        jLabel12.setText("Part Of Hotellerio");

        jLabel13.setText("Amount");

        jLabel14.setText("----------------------------------------------------------------------------------------------------------------------------------");

        jLabel15.setText("01");

        jLabel16.setText("02");

        jLabel17.setText("03");

        jLabel18.setText("04");

        jLabel19.setText("Room Rents");

        jLabel20.setText("Food Bills");

        jLabel21.setText("Laundry");

        jLabel22.setText("Transport");

        jLabel23.setText("----------------------------------------------------------------------------------------------------------------------------------");

        jLabel24.setText("Total Amount");

        jLabel25.setText("less: 10%");

        jLabel26.setText("GST Tax: 12%");

        jLabel27.setText("NetTotal:(Rounded)");

        donedone.setText("Done");
        donedone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donedoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_current, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addComponent(bill_number, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel11)
                        .addGap(124, 124, 124)
                        .addComponent(jLabel12)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(325, 325, 325)
                                .addComponent(id_current, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(160, 160, 160)
                                            .addComponent(jLabel19))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel20)
                                            .addGap(13, 13, 13)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)))
                                    .addComponent(jLabel18))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(transport_rent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(room_rent, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                            .addComponent(laudry_rnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(food_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(laundry_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addGap(88, 88, 88))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel26))
                                    .addGap(40, 40, 40))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total_amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(less, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(net_total, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10)
                            .addComponent(jLabel23)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(donedone))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1)))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)))
                .addGap(244, 244, 244))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(Customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(date_current, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bill_number, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(id_current, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19)
                            .addComponent(room_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel16))
                                    .addComponent(food_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel21)
                                    .addComponent(laudry_rnt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(laundry_rent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22)
                            .addComponent(transport_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel23)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(less, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(gst, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(net_total, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(donedone)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void donedoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donedoneActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.YES_NO_OPTION;
        int y = JOptionPane.showConfirmDialog(this, "Confirm with above details?", "Title on Box", x);
        if(y == 0)
        {
            try {
                Connection co = DBConnect.connect();
                String done = "done";
                int id = Integer.valueOf(id_current.getText());
                String sql = "update payments set  payment_status = ? where cust_id=?";
                PreparedStatement p = co.prepareStatement(sql);
                p.setString(1, done);
                p.setInt(2, id);
                p.executeUpdate();
                JOptionPane.showMessageDialog(null, "payments have been done!", "Display Message", JOptionPane.INFORMATION_MESSAGE);
                String room = "Select single, doubled, douplex from room_details where cust_ID = ?";
                PreparedStatement psr=co.prepareStatement(room);
                psr.setInt(1, id);
                ResultSet rsr=psr.executeQuery();
                int arr[] = new int[3];
                while(rsr.next())
                {
                    arr[0] = rsr.getInt(1);
                    arr[1] = rsr.getInt(2);
                    arr[2] = rsr.getInt(3);
                }
                for(int i=0;i<arr.length;i++)
                {
                    System.out.println(arr[i]);
                    System.out.println();
                }
                String sql2 = "Select SIngle,DOuuble,DOuplex from room_availability where id=?";
                PreparedStatement ps2=co.prepareStatement(sql2);
                ps2.setInt(1, 1);
                ResultSet rs2=ps2.executeQuery();
                int arr1[] = new int[3];
                while(rs2.next())
                {
                    arr1[0] = rs2.getInt(1);
                    arr1[1] = rs2.getInt(2);
                    arr1[2] = rs2.getInt(3);
                }
                for(int i=0;i<arr1.length;i++)
                {
                    System.out.println(arr1[i]);
                    System.out.println();
                }
                int remain[] = new int[3];
                for(int i=0;i<remain.length;i++)
                {
                    remain[i] = arr1[i]+arr[i];
                }
                String remainn = "Update room_availability set SIngle=?,DOuuble=?,DOuplex=? where id=?";
                        PreparedStatement psss  = co.prepareStatement(remainn);
                        psss.setInt(1, remain[0]);
                        psss.setInt(2, remain[1]);
                        psss.setInt(3, remain[2]);
                        psss.setInt(4, 1);
                        psss.executeUpdate();
                        co.close();
            JOptionPane.showMessageDialog(null, "Room details also updated","Display Message",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        else {
            try {
                Connection co = DBConnect.connect();
                String not_done = "not done";
                int id = Integer.valueOf(id_current.getText());
                String sql = "update payments set  payment_status = ? where cust_id=?";
                PreparedStatement p = co.prepareStatement(sql);
                p.setString(1, not_done);
                p.setInt(2, id);
                p.executeUpdate();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_donedoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generate_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Customer_name;
    private javax.swing.JLabel bill_number;
    private javax.swing.JLabel date_current;
    private javax.swing.JButton donedone;
    private javax.swing.JLabel food_rent;
    private javax.swing.JLabel gst;
    private javax.swing.JLabel id_current;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel laudry_rnt;
    private javax.swing.JLabel laundry_rent;
    private javax.swing.JLabel less;
    private javax.swing.JLabel net_total;
    private javax.swing.JLabel room_rent;
    private javax.swing.JLabel total_amount;
    private javax.swing.JLabel transport_rent;
    // End of variables declaration//GEN-END:variables

    
}
