/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotellerio;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author  Hemanth Eagle
 */
public class Room_Allocate extends javax.swing.JFrame {

    /**
     * Creates new form room_Allocate
     */
    public Room_Allocate() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Single = new javax.swing.JTextField();
        Double = new javax.swing.JTextField();
        Douplex = new javax.swing.JTextField();
        Submit_02 = new javax.swing.JButton();
        Reset_02 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        customer_Name = new javax.swing.JTextField();
        cancel_06 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cust_id_err = new javax.swing.JLabel();
        single_err = new javax.swing.JLabel();
        double_err = new javax.swing.JLabel();
        douplex_err = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Single");

        jLabel2.setText("Double");

        jLabel4.setText("Douplex");

        Single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleActionPerformed(evt);
            }
        });
        Single.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SingleKeyTyped(evt);
            }
        });

        Double.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DoubleKeyTyped(evt);
            }
        });

        Douplex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DouplexKeyTyped(evt);
            }
        });

        Submit_02.setText("Submit");
        Submit_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_02ActionPerformed(evt);
            }
        });

        Reset_02.setText("Reset");
        Reset_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_02ActionPerformed(evt);
            }
        });

        jLabel5.setText("Customer ID");

        customer_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_NameActionPerformed(evt);
            }
        });
        customer_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customer_NameKeyTyped(evt);
            }
        });

        cancel_06.setText("Cancel");
        cancel_06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_06ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotellerio/images/bed room.png"))); // NOI18N

        jLabel6.setText("Let  Them Sleep..Freshup Themselves..");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Single, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(single_err, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(cust_id_err, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Double, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(double_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Douplex, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(douplex_err, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancel_06)
                .addGap(63, 63, 63)
                .addComponent(Reset_02)
                .addGap(66, 66, 66)
                .addComponent(Submit_02)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(customer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cust_id_err, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Single, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(single_err, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Double, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(double_err, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Douplex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(douplex_err, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset_02)
                    .addComponent(Submit_02)
                    .addComponent(cancel_06))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SingleActionPerformed

    private void Submit_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_02ActionPerformed
        //int yn = JOptionPane.showConfirmDialog(nul,"Do you want to Continue?", title, WIDTH, HEIGHT) ;
        if(customer_Name.getText().trim().isEmpty() && Single.getText().trim().isEmpty() && Douplex.getText().trim().isEmpty() && Double.getText().trim().isEmpty())
        {
            cust_id_err.setText("*This feild is required");
            cust_id_err.setForeground(Color.red);
            single_err.setText("*This feild is required");
            single_err.setForeground(Color.red);
            double_err.setText("*This feild is required");
            double_err.setForeground(Color.red);
            douplex_err.setText("*This feild is required");
            douplex_err.setForeground(Color.red);
        }
        else if(customer_Name.getText().trim().isEmpty())
        {
            cust_id_err.setText("*This feild is required");
            cust_id_err.setForeground(Color.red);
            single_err.setText("");
            double_err.setText("");
            douplex_err.setText("");
        }
        else if(Single.getText().trim().isEmpty())
        {
            cust_id_err.setText("");
            single_err.setForeground(Color.red);
            single_err.setText("*This feild is required");
            double_err.setText("");
            douplex_err.setText("");
        }
        else if(Double.getText().trim().isEmpty())
        {
            cust_id_err.setText("");
            double_err.setForeground(Color.red);
            single_err.setText("");
            double_err.setText("*This feild is required");
            douplex_err.setText("");
        }
        else if(Douplex.getText().trim().isEmpty())
        {
            cust_id_err.setText("");
            douplex_err.setForeground(Color.red);
            single_err.setText("");
            double_err.setText("");
            douplex_err.setText("*This feild is required");
        }
        else{
            try {
                Connection con1 = DBConnect.connect();
                int customer_id = Integer.valueOf(this.customer_Name.getText());
            String sqlc="select cust_name from customer_details where cust_ID=?";
            PreparedStatement psc = con1.prepareStatement(sqlc);
            psc.setInt(1, customer_id);
            ResultSet rsc = psc.executeQuery();
            if(rsc.next())
            {
                  int sin = Integer.valueOf(Single.getText());
        int dou = Integer.valueOf(Double.getText());
        int doup = Integer.valueOf(Douplex.getText());
        try {
                String sql1 = "Select * from room_rent where ID=?";
                PreparedStatement ps1=con1.prepareStatement(sql1);
                ps1.setInt(1, 1);
                ResultSet rs=ps1.executeQuery();
                int s=0,db=0,dp=0;
                        while(rs.next()){
                             s=rs.getInt(2);
                             db=rs.getInt(3);
                             dp=rs.getInt(4);
                        }
                System.out.println("single"+s+"double"+db+"douplex"+dp);
                int cost_sing = sin*s;
                int cost_doub = dou*db;
                int cost_doup = doup*dp;
                System.out.println(cost_sing+" "+cost_doub+" "+cost_doup );
                
                
                String sql = "insert into room_details values(?,?,?,?,?,?,?)";
                PreparedStatement ps=con1.prepareStatement(sql);
                ps.setInt(1,Integer.valueOf(customer_Name.getText()));
                ps.setInt(2,sin);
                ps.setInt(3,cost_sing);
                ps.setInt(4,dou);
                ps.setInt(5,cost_doub);
                ps.setInt(6,doup);
                ps.setInt(7,cost_doup);
                ps.executeUpdate();
                System.out.println("room records updated");
                updateRoom(sin,dou,doup);
                this.setVisible(false);
            
    }                                         
    catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null, e,"Display Message",JOptionPane.INFORMATION_MESSAGE);
    }
    finally{
            System.out.println("hello");
       
    }
            }
            else{
            JOptionPane.showMessageDialog(null, "There is no customer with given ID.Please Enter details Again","Display Message",JOptionPane.INFORMATION_MESSAGE);
                customer_Name.setText("");
        Single.setText("");
        Double.setText("");
        Douplex.setText("");
        single_err.setText("");
        double_err.setText("");
        douplex_err.setText("");
            }
                
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e,"Display Message",JOptionPane.INFORMATION_MESSAGE);
            }
      }
    }//GEN-LAST:event_Submit_02ActionPerformed

    private void Reset_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_02ActionPerformed
        customer_Name.setText("");
        Single.setText("");
        Double.setText("");
        Douplex.setText("");
        single_err.setText("");
        double_err.setText("");
        douplex_err.setText("");
    }//GEN-LAST:event_Reset_02ActionPerformed

    private void cancel_06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_06ActionPerformed
        this.setVisible(false);
        new Room_Section().setVisible(true);
    }//GEN-LAST:event_cancel_06ActionPerformed

    private void customer_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customer_NameKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_customer_NameKeyTyped

    private void customer_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_NameActionPerformed

    private void SingleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SingleKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_SingleKeyTyped

    private void DoubleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DoubleKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_DoubleKeyTyped

    private void DouplexKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DouplexKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_DouplexKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room_Allocate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room_Allocate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room_Allocate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room_Allocate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room_Allocate().setVisible(true);
            }
        });
    }
    
 static void updateRoom(int a,int b,int d)
 {
            Connection con = DBConnect.connect();
     
     try  {
            int SIngle=0,DOuuble=0,DOuplex=0;
            String sql = " select * from room_availability";
            PreparedStatement ps=con.prepareStatement(sql);
			ResultSet rs=ps.executeQuery();
                        while(rs.next()){
                             SIngle =  rs.getInt(2);
                             DOuuble = rs.getInt(3);
                             DOuplex = rs.getInt(4);
                        }
            //con.close();
            int a1 = SIngle-a;
            int b1= DOuuble-b;
            int d1=DOuplex-d;
            int e1=1;
            String sql1 = "update room_availability set SIngle = ?, DOuuble=?,DOuplex=? where id=?";
            PreparedStatement ps1 = con.prepareStatement(sql1);
            ps1.setInt(1,a1);
            ps1.setInt(2,b1);
            ps1.setInt(3,d1);
            ps1.setInt(4,e1);
            ps1.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null,"room records are updated","Display message", JOptionPane.INFORMATION_MESSAGE);
                    
     } 
        catch (SQLException e) {
            System.out.println("no result found "+e);
        } }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Double;
    private javax.swing.JTextField Douplex;
    private javax.swing.JButton Reset_02;
    private javax.swing.JTextField Single;
    private javax.swing.JButton Submit_02;
    private javax.swing.JButton cancel_06;
    private javax.swing.JLabel cust_id_err;
    private javax.swing.JTextField customer_Name;
    private javax.swing.JLabel double_err;
    private javax.swing.JLabel douplex_err;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel single_err;
    // End of variables declaration//GEN-END:variables
}
